# CI-specific Docker Compose override
# This file extends compose.dev.yaml with CI-specific configurations

services:
  postgres:
    environment:
      POSTGRES_DB: laravel_test
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret  # pragma: allowlist secret
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"

  workspace:
    environment:
      - APP_ENV=testing
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=laravel_test
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret  # pragma: allowlist secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis

  app:
    environment:
      - APP_ENV=testing
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=laravel_test
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret  # pragma: allowlist secret
